name: 'Reliably Actions'
description: 'Use Reliably in your GitHub workflow'
author: 'Reliably'
branding:
  icon: "check-circle"
  color: "red"
runs:
  using: 'docker'
  image: 'docker://ghcr.io/reliablyhq/cli/cli:latest'