name: 'Reliably Experiment Action'
description: 'Run a Reliably Chaos Toolkit experiment'
author: 'Reliably'
branding:
  icon: "check-circle"
  color: "red"
inputs:
  reliably-agent-token:
    description: "Reliably agent authentication token"
    required: true
  reliably-experiment-url:
    description: "Reliably experiment url"
    required: true
  python-version:
    description: "The python version to use to run the Chaos Toolkit"
    required: false
    default: "3.10"
  environment-name:
    description: "Name of a GitHub environment to populate secrets from"
    required: false
runs:
  using: "composite"
  steps:
    - name: Configure Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
    
    - name: Install Chaos Toolkit
      shell: bash
      run: python -m pip install -q --prefer-binary wheel chaostoolkit \
        chaostoolkit-aws \
        chaostoolkit-azure \
        chaostoolkit-kubernetes \
        chaostoolkit-google-cloud-platform \
        chaostoolkit-humio \
        chaostoolkit-prometheus \
        chaostoolkit-toxiproxy \
        chaostoolkit-opentracing \
        chaostoolkit-istio \
        chaostoolkit-wiremock \
        chaostoolkit-gandi \
        chaostoolkit-dynatrace \
        chaostoolkit-k6 \
        chaostoolkit-addons \
        chaostoolkit-grafana \
        chaostoolkit-slack \
        opentelemetry-api \
        opentelemetry-sdk \
        opentelemetry-exporter-otlp-proto-http \
        opentelemetry-propagator-b3 \
        opentelemetry-semantic-conventions

    - name: Add repository top-level ./bin directory to the PATH
      shell: bash
      run: |
        if [[ -d "./bin" ]]; then
          echo "PATH=$PATH:./bin" >> $GITHUB_ENV
        fi
