name: Run the Reliably Agent in your workflow every minute
on:
  schedule:
    - cron:  '1 * * * *'
  
jobs:
  setup-reliably:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Download and install Reliably CLI
        uses: reliablyhq/actions/agent@v1
