name: "Setup Reliably CLI"
description: "Installs a specific version of Reliably"
branding:
  icon: "check-circle"
  color: "red"
inputs:
  python-version:
    description: "Which Python version to use (should be 3.10+)"
    required: false
    default: '3.10'
  reliably-version:
    description: "Which Reliably version to install"
    required: false
    default: 0.1.0
runs:
  using: "composite"
  steps:
      - name: Checkout to get a copy of the Reliably CLI configuration
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Copy configuration if found
        shell: bash
        run: echo "RELIABLY_CLI_CONFIG=.reliably.toml" >> $GITHUB_ENV

      - name: Configure Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'
      
      - name: Install Reliably CLI
        shell: bash
        run: pip install --prefer-binary reliably-cli==${{ inputs.reliably-version }}

      - name: Store Reliably version
        shell: bash
        run: echo ::set-output name=version::"$(reliably version --short)"
