name: Setup Reliably in your workflow
on: push
jobs:
  setup-reliably:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Download and install Reliably CLI
        uses: reliablyhq/actions/setup@v1
